import Link from 'next/link';
import { Screen } from '../components/CommunityUI';

export default function Privacy() {
  return <Screen title="Your data in this preview." intro="Technical information about the current development preview, updated September 26, 2026. This is not a finalized production privacy policy.">
    <div className="ark-reading space-y-8 text-text-secondary">
      <section><h2 className="text-xl mb-3 text-white">Browsing the catalog</h2><p>Catalog queries go through this server to AniList. We send the title or character search, format, sorting choice, page and calendar date, without your account ID or email. Search results are not cached by this application. General catalog pages are reused in server memory for five minutes and calendar pages for one minute. Concurrent requests for the same public page share one upstream request. At most 100 pages are retained; expired entries are removed on the next catalog request, or all entries disappear when the server restarts. Hosting and upstream service logs may have separate retention. Catalog artwork and remote fonts are not loaded by the current interface. Following an external link sends you to that site, which has its own practices.</p></section>
      <section><h2 className="text-xl mb-3 text-white">Accounts and browser storage</h2><p>When connected, Supabase handles email, password authentication and a chosen display name. Its browser client stores a session in local storage to restore sign-in. Signing out removes the local session after a successful sign-out; clearing site data also removes local storage. Neither action deletes your account or published content. The site stores your explicit light or dark appearance choice locally under shonen-ark-appearance. Use device appearance removes that preference; it is not sent to a server. No advertising, analytics SDK, marketing preference or tracking-cookie banner is implemented in the active MVP.</p></section>
      <section><h2 className="text-xl mb-3 text-white">What you publish and save</h2><p>Theories, display names and open gigs are public when published. Private drafts, saved theories and collections are restricted to the account owner by database policies. Contact messages include your account email and are stored for the administrator. Avoid posting sensitive information. The theory page provides deletion, and your saved collection controls let you remove saved items.</p></section>
      <section><h2 className="text-xl mb-3 text-white">Requests and retention</h2><p>Account access, correction and deletion requests need an identified operator and a monitored contact channel before public launch. That channel is not configured in this preview. The <Link href="/contact">account contact form</Link> requires connected account services and is not a substitute for a public privacy-request channel. Automated retention schedules and backup deletion timing are not configured or verified. There is no promise of immediate deletion from backups.</p></section>
    </div>
  </Screen>;
}
